Models/BusinessObjects/Payments/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using resm_app.Models.BusinessObjects.Invoices;
using resm_app.Models.BusinessObjects.Orders;
using resm_app.Models.BusinessObjects.Sections;

namespace resm_app.Models.BusinessObjects.Payments
{
    [Table("CCNS_Payment",Schema="dbo")]
    public class Payment
    {
        [Key]
        [Column(TypeName = "bigint")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long DocEntry { get; set; }
        
        [Column(TypeName = "bigint")]
        [Required]
        public long PaymentCode { get; set; }

        [Column(TypeName = "decimal(18,6)")]
        public decimal DiscPrcnt { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal TotalDiscUSD { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal TotalDiscRiel { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal TaxPrcnt { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal TotalTaxUSD { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal TotalTaxRiel { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal ExchangeRate { get; set; }
        
        [Column(TypeName = "bigint")]
        [Required]
        public long ShiftId { get; set; }

        [Column(TypeName = "nvarchar(125)")]
        public string ShiftStr { get; set; }

        [Column(TypeName = "decimal(18,6)")]
        public decimal ServiceChargeUSD { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal ServiceChargeRiel { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal OtherChargeUSD { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal OtherChargeRiel { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        [Required]
        public decimal SubTotalUSD { get; set; }

        [Column(TypeName = "decimal(18,6)")]
        [Required]
        public decimal SubTotalRiel { get; set; }

        [Column(TypeName = "decimal(18,6)")]
        [Required]
        public decimal GrandTotalUSD { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        [Required]
        public decimal GrandTotalRiel { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal ReceivedUSD { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal ReceivedRiel { get; set; }

        [Column(TypeName = "decimal(18,6)")]
        public decimal ComissionPrcn { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal ComissionRate { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal ComissionUSD { get; set; }
        
        [Column(TypeName = "decimal(18,6)")]
        public decimal ComissionRiel { get; set; }
        
        [Column(TypeName = "bigint")]
        public long ComissionById { get; set; }
        
        [Column(TypeName = "nvarchar(125)")]
        public string ComissionByStr { get; set; }
        
        [Column(TypeName = "bigint")]
        public long BookingId { get; set; }

        [Column(TypeName = "nvarchar(125)")]
        [Required]
        public string BookingStatus { get; set; }
        
        [Column(TypeName = "datetime")]
        public DateTime? PaymentDate { get; set; }
        
        [Column(TypeName = "datetime")]
        public DateTime? PaidDate { get; set; }
        
        [Column(TypeName = "bigint")]
        [Required]
        public long ReceivedById { get; set; }
        
        [Column(TypeName = "nvarchar(125)")]
        public string ReceivedByStr { get; set; }
        
        [Column(TypeName = "bigint")]
        public long MethodTypeId { get; set; }
        
        [Column(TypeName = "nvarchar(125)")]
        public string MethodTypeStr { get; set; }
        
        [Column(TypeName = "nvarchar(1)")]
        public string DocStatus { get; set; }
        
        [Column(TypeName = "nvarchar(1)")]
        public string CancelStatus { get; set; }
        
        [Column(TypeName = "datetime")]
        public DateTime? CancelDate { get; set; }
        
        [Column(TypeName = "bigint")]
        public long CancelById { get; set; }
        
        [Column(TypeName = "nvarchar(125)")]
        public string CancelByStr { get; set; }
        
        [Column(TypeName = "nvarchar(1)")]
        public string Deleted { get; set; }
        
        [Column(TypeName = "nvarchar(225)")]
        public string Description { get; set; }
        
        [Column(TypeName = "nvarchar(1)")]
        public string PayType { get; set; }

        [Column(TypeName = "decimal(18,6)")]
        public decimal Received_USD { get; set; }

        [Column(TypeName = "decimal(18,6)")]
        public decimal Received_Riel { get; set; }

        [NotMapped]
        public IList<PaymentDetail> PaymentDetails { get; set; }
        [NotMapped]
        public Section Section { get; set; }
        [NotMapped]
        public BookingSection BookingSection { get; set; }
        [NotMapped]
        public IList<Invoice> Invoices { get; set; }
    }
}

Models/BusinessObjects/Payments/PaymentMethod.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace resm_app.Models.BusinessObjects.Payments
{
    [Table("CCNS_PaymentMethod",Schema = "dbo")]
    public class PaymentMethod
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(TypeName = "bigint")]
        public long Id { get; set; }
        [Column(TypeName = "nvarchar(125)")]
        public string MethodEn { get; set; }
        [Column(TypeName = "nvarchar(125)")]
        public string MethodStr { get; set; }
        [Column(TypeName = "nvarchar(125)")]
        public string Description { get; set; }
        [Column(TypeName = "nvarchar(1)")]
        public  string Deleted { get; set; }
    }
}

Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using resm_app.Models;
using resm_app.Models.BusinessObjects.Commissions;
using resm_app.Models.BusinessObjects.Invoices;
using resm_app.Models.BusinessObjects.Products;
using resm_app.Models.IBusinessObject;
using resm_app.ViewModels;

namespace resm_app.Controllers
{
    [Authorize]
    [CheckAuthorization]
    public class ReportsController : Controller
    {
        private readonly IInvoice _invoice;
        private readonly IPayment _payment;
        private readonly ISeller _seller;
        private readonly IUser _user;
        private readonly ICommission _commission;
        private readonly IInventory _inventory;
        private readonly ICashInOut _cash;
        private readonly IWebHostEnvironment _hostingEnvironment;


        public ReportsController(IInvoice invoice,IPayment payment,
                                ISeller seller,IUser user,
                                ICommission commission,                                
                                IInventory inventory,
                                ICashInOut cash,
                                IWebHostEnvironment hostingEnvironment)
        {
            _invoice = invoice;
            _payment = payment;
            _seller = seller;
            _user = user;
            _commission = commission;
            _inventory = inventory;
            _cash = cash;
            _hostingEnvironment = hostingEnvironment;
        }
        [HttpGet("report/invoice/pending")]
        public async Task<IActionResult> ReportInvoicePending()
        {
            return View(await _invoice.GetInvoicePending());
        }
        [HttpGet("report/invoices")]
        public IActionResult FindReportInvoice()
        {
            return View();
        }
        [HttpGet("report/payments")]
        public async Task<IActionResult> PaymentReport()
        {
            return View(await _payment.GetPayments());
        }
        [HttpGet("report/payment")]
        public IActionResult FindPaymentReport()
        {
            return View();
        }
        [HttpGet("/report/inv")]
        public async Task<JsonResult> GetInvoiceByDate(string from, string to)
        {
            if (string.IsNullOrEmpty(from) && string.IsNullOrEmpty(to))
            {
                var invs = await _seller.SumValueInvoices(DateTime.Now.Date,DateTime.Now.Date.AddDays(1));
                var invds = new List<InvoiceDetail>();
                foreach (var i in invs)
                {
                    invds.AddRange(i.InvoiceDetails);
                }
                var foods = invds.Where(p => p.Item.CateId == 2).ToList();
                var beverages = invds.Where(p => p.Item.CateId == 3).ToList();
                var services = invs.Sum(p => p.ServiceChargeUSD);
                var otherCharges = invs.Sum(p => p.OtherChargeUSD);
                var sectionAmount = invs.Sum(p => p.SectionAmount);
                
                if (invds.Count > 0)
                {
                   return new JsonResult(new InvoiceViewModel
                   {
                       Food = foods.Sum(p=>p.TotalLine),
                       Beverage = beverages.Sum(p=>p.TotalLine),
                       Service = services,
                       OtherCharge = otherCharges,
                       SectionAmount = sectionAmount
                   });
                }
                else
                {
                    return new JsonResult(new InvoiceViewModel
                    {
                        Food = 0,
                        Beverage = 0,
                        Service = 0,
                        OtherCharge = 0,
                        SectionAmount = 0
                    });
                }
            }
            else
            {
                var dfrm = from.Split("/");
                var dto = to.Split("/");

                var datefrm = dfrm[2] + "-"+ dfrm[0] + "-" + dfrm[1];
                var dateto = dto[2]+ "-"+ dto[0] + "-" + dto[1];
                var invs = await _seller.SumValueInvoices(DateTime.Parse(datefrm),DateTime.Parse(dateto).AddDays(1));
                var invds = new List<InvoiceDetail>();
                foreach (var i in invs)
                {
                    invds.AddRange(i.InvoiceDetails);
                }
                var foods = invds.Where(p => p.Item.CateId == 2).ToList();
                var beverages = invds.Where(p => p.Item.CateId == 3).ToList();
                var services = invs.Sum(p => p.ServiceChargeUSD);
                var otherCharges = invs.Sum(p => p.OtherChargeUSD);
                var sectionAmount = invs.Sum(p => p.SectionAmount);
                
                if (invds.Count > 0)
                {
                    return new JsonResult(new InvoiceViewModel
                    {
                        Food = foods.Sum(p=>p.TotalLine),
                        Beverage = beverages.Sum(p=>p.TotalLine),
                        Service = services,
                        OtherCharge = otherCharges,
                        SectionAmount = sectionAmount
                    });
                }
                else
                {
                    return new JsonResult(new InvoiceViewModel
                    {
                        Food = 0,
                        Beverage = 0,
                        Service = 0,
                        OtherCharge = 0,
                        SectionAmount = 0
                    });
                }
            }
            
        }
        [HttpGet("/report/inv/user")]
        public async Task<JsonResult> GetInvoiceByUserId(string from, string to,long id)
        {
            var emp = await _user.GetEmployee(id);
            if (string.IsNullOrEmpty(from) && string.IsNullOrEmpty(to))
            {
                var invs = await _seller.GetInvoicesByUserId(DateTime.Now.Date,DateTime.Now.Date.AddDays(1),id);
                var invds = new List<InvoiceDetail>();
                foreach (var i in invs)
                {
                    invds.AddRange(i.InvoiceDetails);
                }
                var foods = invds.Where(p => p.Item.CateId == 2).ToList();
                var beverages = invds.Where(p => p.Item.CateId == 3).ToList();
                var services = invs.Sum(p => p.ServiceChargeUSD);
                var otherCharges = invs.Sum(p => p.OtherChargeUSD);
                var sectionAmount = invs.Sum(p => p.SectionAmount);
                var inv = new InvoiceViewModel
                {
                    Food = foods.Sum(p=>p.TotalLine),
                    FoodQty = foods.Sum(p=>p.Quantity),
                    Beverage = beverages.Sum(p=>p.TotalLine),
                    BeverageQty = beverages.Sum(p=>p.Quantity),
                    Service = services,
                    OtherCharge = otherCharges,
                    SectionAmount = sectionAmount,
                    Employee = emp
                };
                return new JsonResult(inv);
            }
            else
            {
                var dfrm = from.Split("/");
                var dto = to.Split("/");

                var datefrm = dfrm[2] + "-"+ dfrm[0] + "-" + dfrm[1];
                var dateto = dto[2]+ "-"+ dto[0] + "-" + dto[1];
                var invs = await _seller.GetInvoicesByUserId(DateTime.Parse(datefrm),DateTime.Parse(dateto).AddDays(1),id);
                var invds = new List<InvoiceDetail>();
                foreach (var i in invs)
                {
                    invds.AddRange(i.InvoiceDetails);
                }
                var foods = invds.Where(p => p.Item.CateId == 2).ToList();
                var beverages = invds.Where(p => p.Item.CateId == 3).ToList();
                var services = invs.Sum(p => p.ServiceChargeUSD);
                var otherCharges = invs.Sum(p => p.OtherChargeUSD);
                var sectionAmount = invs.Sum(p => p.SectionAmount);
            
                var inv = new InvoiceViewModel
                {
                    Food = foods.Sum(p=>p.TotalLine),
                    FoodQty = foods.Sum(p=>p.Quantity),
                    Beverage = beverages.Sum(p=>p.TotalLine),
                    BeverageQty = beverages.Sum(p=>p.Quantity),
                    Service = services,
                    OtherCharge = otherCharges,
                    SectionAmount = sectionAmount,
                    Employee = emp
                };
                return new JsonResult(inv);
            }
        }
        [HttpGet("report/order/value")]
        public async Task<decimal> GetValueOrder()
        {
            var orders = await _seller.SumGrandTotalOrder();
            return orders.Sum(p => p.GrandTotalUSD);
        }
        [HttpGet("report/invoice/value")]
        public async Task<decimal> GetValueInvoice()
        {
            var orders = await _seller.SumGrandTotalInvoice();
            return orders.Sum(p => p.GrandTotalUSD);
        }
        [HttpGet("report/booked/value")]
        public async Task<int> GetCountBooked()
        {
            return await _seller.CountSectionBooked();
        }
        [HttpGet("report/checked/value")]
        public async Task<int> GetCountChecked()
        {
            return await _seller.CountSectionCheckIn();
        }
        [HttpGet("report/top/sale")]
        public async Task<JsonResult> GetTopSale()
        {
            return new JsonResult(await _seller.GetTopSale());
        }
        [HttpGet("report/purchase")]

Views/Payments/_PaymentAuthorizePartailAsync.cshtml
<form>
    <fieldset>
        <legend>Authorize</legend>
        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Sub Total</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Discount</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Total Discount</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-6 col-form-label">VAT</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Total VAT</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Other Charge</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Service Charge</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>

    </fieldset>
    <fieldset>
        <legend>Total Receive</legend>
        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Received Dollars</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Received Riels</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>
    </fieldset>
    <fieldset>
        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Total</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Grand Total</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-6 col-form-label">Exchange Rate</label>
            <div class="col-sm-6">
                <input type="text" class="form-control form-control-sm text-right form-bg-info" value="0.00">
            </div>
        </div>

    </fieldset>
    <fieldset>
        <div class="form-group">
            <div class="pull-right">
                <a asp-action="Order" asp-controller="poss" role="button" class="btn btn-secondary">Back</a>
                <a asp-action="Order" asp-controller="poss" role="button" class="btn btn-primary">Print</a>
            </div>
        </div>
    </fieldset>
</form>
                        
                        

Views/Payments/_PaymentCreditByCashPartailAsync.cshtml
@using System.Globalization
@{
    var invoice = ViewBag.CreditInvoice; 
}
<form id="frm-total-payment-footer" style="background-color: #ffffff;padding: 5px 5px;">
    <fieldset>
        <legend>Cash</legend>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Sub Total </label>
            <label class="col-sm-1 text-right">($)</label>
            <div class="col-sm-6">
                <input type="text" id="sub_total" readonly="readonly" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="@String.Format("{0:N2}", @invoice.SubTotalUSD)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Free Hour</label>
            <label class="col-sm-1 text-right">(h)</label>
            <div class="col-sm-6">
                <input type="text" id="free-hour" readonly="readonly"  style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="@String.Format("{0:N2}",invoice.FreeHour)">
            </div>
        </div>
        
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Discount </label>
            <label class="col-sm-1 text-right">(%)</label>
            <div class="col-sm-6">
                <input type="text" id="discount_percent" readonly="readonly" onblur="blur_discount_percent(this)" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="@String.Format("{0:N2}",@invoice.DiscPrcnt)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Total Discount </label>
            <label class="col-sm-1 text-right">($)</label>
            <div class="col-sm-6">
                <input type="text" id="discount_dollar" readonly="readonly" onblur="blur_discount(this)" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="@String.Format("{0:N2}",@invoice.TotalDiscUSD)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">VAT </label>
            <label class="col-sm-1 text-right">(%)</label>
            <div class="col-sm-6">
                <input type="text" id="vat_percent" readonly="readonly" onblur="blur_vat_percent(this)" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="@String.Format("{0:N2}",@invoice.TaxPrcnt)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Total VAT </label>
            <label class="col-sm-1 text-right">($)</label>
            <div class="col-sm-6">
                <input type="text" id="vat_dollar" readonly="readonly" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="0.00">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Other Charge </label>
            <label class="col-sm-1 text-right">($)</label>
            <div class="col-sm-6">
                <input type="text" id="other_charge" readonly="readonly" onblur="blur_charge(this)" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="@String.Format("{0:N2}",@invoice.OtherChargeUSD)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Service Charge </label>
            <label class="col-sm-1 text-right">($)</label>
            <div class="col-sm-6">
                <input type="text" id="service_charge" readonly="readonly" onblur="blur_charge(this)" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="@String.Format("{0:N2}",@invoice.ServiceChargeUSD)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Grand Total </label>
            <label class="col-sm-1 text-right">($)</label>
            <div class="col-sm-6">
                <input type="text" id="grand_total" readonly="readonly" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="@String.Format("{0:N2}",@invoice.GrandTotalUSD)">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Grand Total</label>
            <label class="col-sm-1 text-right">(៛)</label>
            <div class="col-sm-6">
                <input type="text" id="grand_total_riel" readonly="readonly" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value=" @invoice.GrandTotalRiel.ToString("N2", CultureInfo.InvariantCulture);)">
            </div>
        </div>

    </fieldset>
    <fieldset>
        <legend>Total Receive</legend>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Received Dollars </label>
            <label class="col-sm-1 text-right">($)</label>
            <div class="col-sm-6">
                <input type="text" id="receive_dollar" onblur="blur_receive(this)" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="0.00">
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Received Riels </label>
            <label class="col-sm-1 text-right">(៛)</label>
            <div class="col-sm-6">
                <input type="text" id="receive_reil" onblur="blur_receive(this)" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="0.00">
            </div>
        </div>
    </fieldset>
    <fieldset>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Exchange Dollars</label>
            <label class="col-sm-1 text-right">($)</label>
            <div class="col-sm-6">
                <input type="text" id="exchange" readonly="readonly" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="0.00">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Exchange Riels</label>
            <label class="col-sm-1 text-right">(៛)</label>
            <div class="col-sm-6">
                <input type="text" id="exchange_reil" readonly="readonly"  style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="0.00">
            </div>
        </div>
        <div class="form-group row commission">
            <label class="col-sm-5 col-form-label">Commission</label>
            <label class="col-sm-1 text-right">(%)</label>
            <div class="col-sm-6">
                <input type="text" id="commission" @ViewBag.CommissionCheck onblur="blur_commission(this)" style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="0.00">
            </div>
        </div>
        
        <div class="form-group row commission">
            <label class="col-sm-5 col-form-label">Commission Amount</label>
            <label class="col-sm-1 text-right">($)</label>
            <div class="col-sm-6">
                <input type="text" id="commission_amount" @ViewBag.CommissionCheck onblur="blur_commission_amount(this)"  style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="0.00">
            </div>
        </div>
        
        <div class="form-group row">
            <label class="col-sm-5 col-form-label">Exchange Rate 1$ = </label>
            <label class="col-sm-1 text-right">(៛)</label>
            <div class="col-sm-6">
                <input type="text" id="exchange_rate" readonly="readonly"  style="font-weight: bold;" class="form-control form-control-sm text-right form-bg-info text-dark" value="@Convert.ToDecimal(Context.Session.GetString("Riel")).ToString("0.00")">
            </div>
        </div>
    </fieldset>
    <br/>
    <fieldset>
        <div class="form-group">
            <div class="pull-right">
            @*data-toggle="modal" data-target="#modal-print-payment"*@
                <a  role="button" class="btn btn-primary text-white" onclick="onClickPrintCreditPayment();">Pay</a>
                <a asp-action="SaleAging" asp-controller="Reports" role="button" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </fieldset>
</form>