Controllers/ExchRatesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using resm_app.Models;
using resm_app.Models.BusinessObjects.Exchanges;
using resm_app.Models.IBusinessObject;

namespace resm_app.Controllers
{
    [Authorize]
    [CheckAuthorization]
    public class ExchRatesController : Controller
    {
        private readonly IExchRate<Exchange> _exch;

        public ExchRatesController(IExchRate<Exchange> exch)
        {
            _exch = exch;
        }
        [HttpGet("exch/add")]
        public IActionResult Add()
        {
            return View();
        }
        [HttpGet("/exch/list")]
        public async Task<IActionResult> List()
        {
            ViewBag.Exchagne = await _exch.GetExchRates();
            return View();
        }
        [HttpPost("/exch/add")]
        public async Task<IActionResult> Add(Exchange exchange)
        {
            var usId = int.Parse(HttpContext.Session.GetString("OwnnerId"));
            var usName = HttpContext.Session.GetString("OwnnerName");
            if (ModelState.IsValid)
            {
                exchange.Created_By_Id = usId;
                exchange.Created_By_Name = usName;
                exchange.Created_Date = DateTime.Now;
                exchange.Deleted = "N";
                
                await _exch.InsertExchRate(exchange);
                return Redirect("/exch/list");
            }
            return View();
        }
        [HttpGet("/exch/edit")]
        public async Task<IActionResult> Edit(long id)
        {
            var ex = await _exch.GetExchRate(id);
            return View(ex);
        }
        [HttpPost("/exch/edit")]
        public async Task<IActionResult> Edit(long id,Exchange ex)
        {
            var usId = int.Parse(HttpContext.Session.GetString("OwnnerId"));
            var usName = HttpContext.Session.GetString("OwnnerName");
            if (ModelState.IsValid)
            {
                ex.Updated_By_Id = usId;
                ex.Updated_By_Name = usName;
                ex.Updated_Date = DateTime.Now;
                id = ex.Id;
                await _exch.UpdateExchRate(id,ex);
                
                return Redirect("/exch/list");
            }
            return View();
        }
        [HttpPost("/exch/delete/{id}")]
        public async Task<IActionResult> Delete(long id)
        {
            var ex=new Exchange();
            var usId = int.Parse(HttpContext.Session.GetString("OwnnerId"));
            var usName = HttpContext.Session.GetString("OwnnerName");
            if (ModelState.IsValid)
            {
                ex.Deleted_By_Id = usId;
                ex.Deleted_By_Name = usName;
                ex.Deleted_Date = DateTime.Now;
                
                await _exch.DeleteExch(id,ex);
            }
            return Ok();
        }
        [HttpPost("/exch/set/{id}")]
        public async Task<IActionResult> SetDefault(long id)
        { 
            var ex=new Exchange();
            var usId=int.Parse(HttpContext.Session.GetString("OwnnerId"));
            var usName=HttpContext.Session.GetString("OwnnerName");
            ex.Updated_By_Id = usId;
            ex.Updated_By_Name = usName;    
            ex.Updated_Date=DateTime.Now;
           
            await _exch.SetExchRate(id,ex);
            return Ok();
        }
    }
}

Views/ExchRates/Add.cshtml
@model Exchange
<!-- Page-header start -->

<div class="page-header ribbon-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>Exchange Rate</h4>
                    <span>Edit Exchange Rate</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a asp-action="index" asp-controller="Home"> <i class="icofont icofont-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a>Exchange Rate</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Create</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->

<div class="row">
    <div class="col-sm-12">
        <!-- Basic Form Inputs card start -->
        <div class="card">
            <div class="card-block">
                <h4 class="sub-title" style="border-bottom:2px #00ACED solid ">Edit Exchange Rate Form</h4>
                <form asp-action="Add" asp-controller="ExchRates" role="form" method="post" enctype="multipart/form-data">

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="ExStr">Description <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="ExStr" class="form-control" required="required" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="Dollar">Dollar<span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="Dollar" class="form-control" value="1.000000" required="required" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="Riel">Riel <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="Riel" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="Started">Start Date <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <input asp-for="Started" type="text" class="form-control birthdate" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="Start_Time">Start Time <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <div class="input-group date datetimepicker3">
                                <input type="text" class="form-control" asp-for="Start_Time" required="required" />
                                <span class="input-group-addon ">
                                    <span class="icofont icofont-ui-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="End">End Date <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <input asp-for="End" type="text" class="form-control birthdate" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="End_Time">End Time <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <div class="input-group date datetimepicker3">
                                <input type="text" class="form-control" asp-for="End_Time" required="required" />
                                <span class="input-group-addon ">
                                    <span class="icofont icofont-ui-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


























Views/ExchRates/Edit.cshtml
@model Exchange
<!-- Page-header start -->
<div class="page-header ribbon-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>Exchange Rate</h4>
                    <span>Edit Exchange Rate</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a asp-action="index" asp-controller="Home"> <i class="icofont icofont-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a>Exchange Rate</a>
                    </li>
                     <li class="breadcrumb-item">
                        <a href="#!">Edit</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->

<div class="row">
    <div class="col-sm-12">
        <!-- Basic Form Inputs card start -->
        <div class="card">
            <div class="card-block">
                <h4 class="sub-title" style="border-bottom:2px #00ACED solid ">Edit Exchange Rate Form</h4>
                <form asp-action="Edit" asp-controller="ExchRates" role="form" method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="Id"/>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="ExStr">Description <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="ExStr" class="form-control" required="required"/>
                        </div>
                    </div>
                                   
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="Dollar">Dollar<span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="Dollar" class="form-control" value="1.000000" required="required"/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="Riel">Riel <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <input type="text" asp-for="Riel" class="form-control"/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="Started">Start Date <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <input asp-for="Started"  value="@Model.Started?.ToString("MM/dd/yyyy")" type="text" class="form-control birthdate"/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="Start_Time">Start Time <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <div class="input-group date datetimepicker3">
                                <input type="text" class="form-control" asp-for="Start_Time" required="required"/>
                                <span class="input-group-addon ">
                                    <span class="icofont icofont-ui-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="End">End Date <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <input asp-for="End"  value="@Model.End?.ToString("MM/dd/yyyy")" type="text" class="form-control birthdate"/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" asp-for="End_Time">End Time <span class="text-danger">*</span></label>
                        <div class="col-sm-10">
                            <div class="input-group date datetimepicker3">
                                <input type="text" class="form-control" asp-for="End_Time" required="required"/>
                                <span class="input-group-addon ">
                                    <span class="icofont icofont-ui-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <button type="submit" class="btn btn-success">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/ExchRates/List.cshtml
@using resm_app.Models.BusinessObjects.Exchanges


    <div class="page-header ribbon-header">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <div class="d-inline">
                        <h4>Exchange Rate</h4>
                        <span>Exchange Rate Lists</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="page-header-breadcrumb">
                    <ul class="breadcrumb-title">
                        <li class="breadcrumb-item">
                            <a asp-action="index" asp-controller="Home"> <i class="icofont icofont-home"></i> </a>
                        </li>
                        <li class="breadcrumb-item">
                            <a>Exchange Rate</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="#!">Lists</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

<div class="card">
    <div class="card-header">
        <div class="text-right no-padding">
            <button type="button" asp-action="Add" asp-controller="ExchRates" class="btn btn-primary waves-effect">Create New</button>
        </div>
        
        <h4 class="sub-title" style="border-bottom:2px #00ACED solid ">Exchange Lists</h4>
    </div>
    <div class="card-block">
        <div class="dt-responsive table-responsive">
            <table id="footer-select" class="table table-striped table-bordered nowrap">
                <thead>
                <tr>
                    <th>N<sup>o</sup></th>
                    <th>Description</th>
                    <th>Dollar</th>
                    <th>Riel</th>
                    <th>Start Date</th>
                    <th>Start Time</th>
                    <th>End Date</th>
                    <th>End Time</th>
                    <th class="text-right">Action</th>
                </tr>
                </thead>
                <tbody>
                @{ int i = 1;}
                @foreach (var c in ViewBag.Exchagne as List<Exchange>)
                {
                    <tr>
                        <td>@i</td>
                        <td>@c.ExStr</td>
                        <td>@c.Dollar</td>
                        <td>@c.Riel</td>
                        <td>@c.Started?.ToString("yyyy/MM/dd")</td>
                        <td>@c.Start_Time</td>
                        <td>@c.End?.ToString("yyyy/MM/dd")</td>
                        <td>@c.End_Time</td>
                        @if (c.Default == "Y")
                        {
                            <td class="text-right">
                                <a class="btn-success btn-sm text-white"><i class="icofont icofont-check-circled text-center"></i></a>
                                @*<a class="btn-info btn-sm text-white" asp-action="Edit" asp-controller="ExchRates" asp-route-id="@c.Id">Edit</a>|
                                <a class="btn-danger btn-sm waves-effect md-trigger text-white" onclick="deletecompany(@c.Id);">Delete</a>*@
                            </td>
                        }
                        else
                        {
                            <td class="text-right">
                                <a class="btn-danger btn-sm text-white" onclick="setExchange(@c.Id)"><i class="icofont icofont-eye-alt"></i></a> |
                                <a class="btn-info btn-sm text-white" asp-action="Edit" asp-controller="ExchRates" asp-route-id="@c.Id">Edit</a>|
                                <a class="btn-danger btn-sm waves-effect md-trigger text-white" onclick="deleteExchange(@c.Id);">Delete</a>
                            </td>
                        }
                        
                    </tr>
                    i++;
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="~/js/exchangerate.js"></script>